version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    command: bash -c 'cd /project && composer install && php vendor/bin/codecept build -c tests/integration/ && php vendor/bin/codecept run -c tests/integration/ && vendor/bin/phpunit tests/unit/'
    volumes:
      - ./:/project
    depends_on:
      - chrome
      - httpserver
    network_mode: host
  chrome:
    build:
      context: ./docker
      dockerfile: chrome.docker
    ports:
      - '4444:4444'
    environment:
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_OVERRIDE_MAX_SESSIONS: 'true'
  httpserver:
    build:
      context: ./docker
      dockerfile: httpServer.docker
    volumes:
      - ./tests/integration/html:/public
    ports:
      - '8080:8080'
